### ISSUE TITLE
Dependency on npx

### ISSUE THREAD

**Issue by LaurensRietveld** [jeffwcx/inquirer-select-pro#4]
I noticed there is a `preinstall` hook that uses npx. This causes issues when you install the package in an environment without npm/npx (e.g. a slimmed down docker image that uses yarn for installing)

**Comment by jeffwcx** [comment]
ok, I will remove it.

**Comment by LaurensRietveld** [comment]
That was very quick, thanks, much appreciated :pray:

**Comment by jeffwcx** [comment]
Hi! I have released [v1.0.0-alpha.7](https://github.com/jeffwcx/inquirer-select-pro/releases/tag/v1.0.0-alpha.7). You can check if the issue is resolved. If it is, I will close the issue.

**Comment by LaurensRietveld** [comment]
works great @jeffwcx , thanks :+1:
